# -*- coding: utf-8 -*-
"""Lab_22-05-24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSoUUHWryWu5iKi_9O2mMgrwJWiafZdK
"""

class Fraction:
  def __init__(self, numerator, denominator):

    if denominator == 0:
      raise ZeroDivisionError("Denominator cannot be zero")
    self.numerator = numerator
    self.denominator = denominator

  def __str__(self):
    return f"{self.numerator}/{self.denominator}"

  def to_float(self):
    return self.numerator / self.denominator

fraction = Fraction(1, 3)

print("Fraction :", fraction)
print("Fraction as float:", fraction.to_float())